name: cpu_management
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # flutter_localization: ^0.2.2
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  responsive_sizer: ^3.3.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.2
  retry: ^3.1.2
  otp_autofill: ^4.1.0
  otp_text_field_v2:
    path: packages/otp_text_field_v2
  loader_overlay: ^4.0.0
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  firebase_crashlytics: ^4.0.0
  firebase_analytics: ^11.0.0
  geolocator: ^12.0.0
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^15.0.0
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  web_socket_channel: ^3.0.0
  image_picker: ^1.1.1
  multiple_image_camera: ^0.0.2
  image: ^4.2.0
  image_cropper: ^8.0.2
  timer_count_down: ^2.2.2
  fl_chart: ^0.66.1
  # http: ^1.0.0
  # camera: ^0.10.0+1
  # flutter_image_compress: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/


