// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYEmPJbUeRd0quTTKAB6fAf2uqxvNCw48',
    appId: '1:774913080741:web:3874fd145c4be3fc757c4c',
    messagingSenderId: '774913080741',
    projectId: 'charging-7234a',
    authDomain: 'charging-7234a.firebaseapp.com',
    storageBucket: 'charging-7234a.appspot.com',
    measurementId: 'G-GVV3Y87J1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-lHqbRRt9ysgOvxAwxHIfs4xgdprZ4E',
    appId: '1:774913080741:android:c18be6acb50a966b757c4c',
    messagingSenderId: '774913080741',
    projectId: 'charging-7234a',
    storageBucket: 'charging-7234a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNttBqSh3euVToe5p2a2M8CPgt6BjOvUg',
    appId: '1:774913080741:ios:db6e8fd422e9015e757c4c',
    messagingSenderId: '774913080741',
    projectId: 'charging-7234a',
    storageBucket: 'charging-7234a.appspot.com',
    androidClientId: '774913080741-8ssccdp3ahkgk3tgjvapmuqt97kotqje.apps.googleusercontent.com',
    iosClientId: '774913080741-ie2nq5ufu3er63mqoac2ru66upss47li.apps.googleusercontent.com',
    iosBundleId: 'com.one.onecstation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNttBqSh3euVToe5p2a2M8CPgt6BjOvUg',
    appId: '1:774913080741:ios:b4fa6f6d2d40ebfb757c4c',
    messagingSenderId: '774913080741',
    projectId: 'charging-7234a',
    storageBucket: 'charging-7234a.appspot.com',
    androidClientId:
        '774913080741-8ssccdp3ahkgk3tgjvapmuqt97kotqje.apps.googleusercontent.com',
    iosClientId:
        '774913080741-2ns2o1flj474413hth21cchcgvfku9ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.onecharging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYEmPJbUeRd0quTTKAB6fAf2uqxvNCw48',
    appId: '1:774913080741:web:81b889c69399d66d757c4c',
    messagingSenderId: '774913080741',
    projectId: 'charging-7234a',
    authDomain: 'charging-7234a.firebaseapp.com',
    storageBucket: 'charging-7234a.appspot.com',
    measurementId: 'G-MXDDTCE9Z3',
  );
}